.PHONY: all clear
.DEFAULT_GOAL := all

# Project name
PROJ_NAME := erisa

# Source files
SRC := main.c pipeline.c registers.c

# Generated source files
GEN_SRC := isa.h

# Add the src/ prefix
SRC := $(addprefix src/, $(SRC))
GEN_SRC := $(addprefix src/, $(GEN_SRC))

# Generate object and dependency files from source files
OBJ := $(patsubst src/%.c,build/%.o, $(SRC))
DEP := $(patsubst src/%.c,build/%.d, $(SRC))

CFLAGS := -Wall -Wextra -Werror -Wno-unused -pedantic -std=c99 -ffile-prefix-map=./=/

include $(DEP)

# Each dependency file is generated from the source file
build/%.d: src/%.c build $(GEN_SRC)
	@echo -e "[DEP] $@"
	@$(CC) -MM -MT $(patsubst src/%.c,build/%.o, $<) $< > $@

build/%.o: src/%.c
	@echo -e "[CC] $@"
	@$(CC) $(CFLAGS) -c $< -o $@

build/$(PROJ_NAME)-exec: $(OBJ)
	@echo -e "[LD] $@"
	@$(CC) $(CFLAGS) $^ -o $@

build:
	@echo -e "[DIR] $@"
	@mkdir -p build

all: build build/$(PROJ_NAME)-exec

# Autogenerated files
$(GEN_SRC): codegen.py
	@echo -e "[GEN] $@"
	@python -c 'from codegen import *; targets["$@"]()'

src/isa.h: src/isa.h.in data/isa.yaml

clear:
	rm build $(GEN_SRC) -rf
